### ISSUE TITLE
Is there a good way to embed a cosmoscope? 

### ISSUE THREAD

**Issue by ghost** [graphlab-fr/cosma#105]
### Which part of Cosma is your request about?

- [ ] command-line interface
- [X] cosmoscope (HTML file)
- [ ] documentation
- [ ] other

### Describe your request:

I tried displaying it in an iframe, and that works, but the layout is ill suited for it. I wish I could just embed the main graph part and hide the controls. Is there a way to do that? Or something similar (like deleting parts of the `cosmoscope.html` file)?

This is a SUPER cool tool. Way to go Cosma team.

Thanks!

**Comment by infologie** [comment]
@certainlyNotHeisenberg An immediate, easy solution: you can use custom CSS to permanently hide things.

- First create a CSS file, you can name it however you want, e.g. `styles.css`.
- In the file, add declarations where you select things you want to hide. If you want to hide the left panel (Menu) and graph controls:

```css
aside#menu-container,
button#close-left-side,
div.graph-controls {
  display: none;
}
```

or the left panel and its button but keep the graph controls:

```css
aside#menu-container,
button#close-left-side {
  display: none;
}
div.graph-controls {
  left: 4rem;
}
```

- In your `config.yml`, add the path to that file:

```yaml
css_custom: styles.css
```

- Run `cosma modelize --custom-css`.

But this gets me thinking: we could add an option to have the Menu panel hidden by default, something like this:

```yaml
hide_menu_by_default: true
```

This would allow you to embed a cosmoscope with the Menu hidden but still have the option to quickly toggle it if needed.

Anyway, tell me if this helps!
