### ISSUE TITLE
[Bug] Arrow tip color does not update on highlight

### ISSUE THREAD

**Issue by IgnacioHeredia** [graphlab-fr/cosma#118]
### What version of Cosma are you using?

Cosma 2.4.0

### On which operating system(s) did you observe the bug?

- [ ] macOS
- [ ] Windows
- [X] Linux

### What version of the operating system are you on?

Ubuntu 20.04

### Actions leading to the bug

In my config I have customized both the link color (gray) and the color on highlight (yellow)
```yml
link_types:
  undefined:
    stroke: simple
    color: "#636363"
graph_highlight_color: "#f5ed00"
```

### Bug description

When highlighting a link, the link changes color (as expected) but the arrow tip stays in the original color (gray).

![image](https://github.com/graphlab-fr/cosma/assets/16413205/9c18b68e-5114-4ac2-ba58-d8759ac568a1)

### Additional information

Not a big issue for me, as I don't really care about directionality, but just thought of letting you know. ;)
