### ISSUE TITLE
[Enhancement] Detect `#tags` for customization

### ISSUE THREAD

**Issue by IgnacioHeredia** [graphlab-fr/cosma#40]
### Which part of Cosma is your request about?

- [ ] GUI version (Electron-based app)
- [ ] CLI version (command-line tool)
- [ ] cosmograph (records & cosmoscope creation)
- [X] cosmoscope (exported graph & records)
- [ ] documentation
- [ ] other

### Describe your request:

A minor enhancement for the future.
It would be nice to detect tags in the text (like Zettlr does), so that they could be formatted and rendered nicely. 

## Cosma current behaviour
![image](https://github.com/graphlab-fr/cosma/assets/16413205/390785fd-0be0-493f-b7c9-d98cf72f8a69)

`#toread` tag is treated as normal text.

## Zettlr behaviour

Zettlr detects the tag and exposes it via the `.cm-zkn-tag` CSS class. This allows to customize the rendering:

```css
body.dark #editor .CodeMirror .cm-zkn-tag {
   background-color: rgba(275,171,171, 1);
   color: rgba(138,0,0, 1);
   padding: 2px;
   border-radius:5px;
}
```
![image](https://github.com/graphlab-fr/cosma/assets/16413205/2b89507e-6035-49ef-a9f1-b1363536c19a)

In addition, to `.cm-zkn-tag`, Zettlr also generates additional classes for each tag (eg. `.cm-zkn-tag-toread`) so that they can be customized separately.

![image](https://github.com/graphlab-fr/cosma/assets/16413205/66cbf784-23b2-45f0-935b-ec4eda074435)

Anyway, this is not a priority, just thought it could a nice addition. Thanks!
